server:
  port: 8282

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: clients
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
          filters:
            - RewritePath=/client-service/(?<path>.*), /$\{path}
        - id: sales
          uri: lb://sales-service
          predicates:
            - Path=/sales-service/**
          filters:
            - RewritePath=/sales-service/(?<path>.*), /$\{path}

